// 약 데이터베이스 (약 데이터)
const drugDatabase = [
  { name: '타이레놀', description: '해열 진통제입니다.' },
  { name: '아스피린', description: '통증 및 염증을 완화하는 약입니다.' },
  { name: '비타민 C', description: '면역 체계를 강화해주는 비타민입니다.' },
  { name: '이부프로펜', description: '진통, 항염, 해열 효과를 가진 약입니다.' },
  { name: '나프록센', description: '통증 및 염증을 완화하는 비스테로이드성 항염증제입니다.' },
  { name: '디클로페낙', description: '항염증 및 진통 효과가 있습니다.' },
  { name: '덱시부프로펜', description: '이부프로펜의 활성 성분으로, 진통 및 항염 효과를 제공합니다.' },
  { name: '트라마돌', description: '중증 통증을 완화하는 약물입니다.' },
  { name: '모르핀', description: '강력한 마약성 진통제입니다.' },
  { name: '코데인', description: '중등도 통증 완화와 기침 억제 효과가 있습니다.' },
  { name: '메타돈', description: '중증 통증 완화와 마약 중독 치료에 사용됩니다.' },
  { name: '옥시코돈', description: '중증 통증을 완화하는 마약성 진통제입니다.' },
  { name: '플루옥세틴', description: '우울증 치료에 사용되는 SSRI 계열의 항우울제입니다.' },
  { name: '파록세틴', description: '우울증과 불안 장애 치료에 효과적인 SSRI 계열 약물입니다.' },
  { name: '설트랄린', description: '우울증 및 불안 장애를 치료하는 SSRI 계열의 항우울제입니다.' },
  { name: '에스시탈로프람', description: '우울증과 불안 장애를 치료하는 SSRI 항우울제입니다.' },
  { name: '미르타자핀', description: '우울증 치료와 수면 개선에 도움을 줍니다.' },
  { name: '아미트립틸린', description: '신경성 통증과 우울증 치료에 사용되는 삼환계 항우울제입니다.' },
  { name: '발프로산', description: '간질과 양극성 장애를 치료하는 항간질제입니다.' },
  { name: '카바마제핀', description: '간질과 삼차신경통 치료에 사용되는 항간질제입니다.' },
  { name: '라모트리진', description: '간질과 양극성 장애 치료에 효과적입니다.' },
  { name: '가바펜틴', description: '신경통과 간질을 치료하는 약물입니다.' },
  { name: '프레가발린', description: '신경통, 간질, 불안 치료에 사용됩니다.' },
  { name: '리보트릴', description: '간질 치료와 불안 장애 치료에 효과적인 항간질제입니다.' },
  { name: '디아제팜', description: '불안 완화와 근육 이완에 사용되는 벤조디아제핀 계열 약물입니다.' },
  { name: '로라제팜', description: '불안 완화와 수면 유도에 사용되는 약물입니다.' },
  { name: '알프라졸람', description: '불안 장애와 공황장애를 치료하는 약물입니다.' },
  { name: '프로프라놀롤', description: '고혈압 및 부정맥 치료에 사용되는 베타 차단제입니다.' },
  { name: '아테놀롤', description: '고혈압과 협심증 치료에 사용되는 베타 차단제입니다.' },
  { name: '비소프롤롤', description: '고혈압 및 심부전 치료에 사용되는 베타 차단제입니다.' },
  { name: '칸데사르탄', description: '고혈압과 심부전 치료에 효과적인 혈관 확장제입니다.' },
  { name: '로사르탄', description: '고혈압과 심부전을 치료하는 혈관 확장제입니다.' },
  { name: '에날라프릴', description: '고혈압과 심부전 치료에 사용되는 ACE 억제제입니다.' },
  { name: '라미프릴', description: '고혈압과 심부전 치료에 사용되는 ACE 억제제입니다.' },
  { name: '암로디핀', description: '고혈압과 협심증 치료에 사용되는 칼슘 채널 차단제입니다.' },
  { name: '니페디핀', description: '고혈압과 협심증 치료에 효과적인 칼슘 채널 차단제입니다.' },
  { name: '후로세미드', description: '체액 저류와 고혈압을 치료하는 이뇨제입니다.' },
  { name: '히드로클로로티아지드', description: '고혈압 치료에 사용되는 이뇨제입니다.' },
  { name: '스피로놀락톤', description: '고혈압과 심부전 치료에 사용되는 이뇨제입니다.' },
  { name: '메토프로롤', description: '고혈압과 협심증 치료에 사용되는 베타 차단제입니다.' },
  { name: '클로피도그렐', description: '혈전 예방에 사용되는 항혈소판제입니다.' },
  { name: '와파린', description: '혈전 예방에 사용되는 항응고제입니다.' },
  { name: '리바록사반', description: '혈전 예방을 위한 경구용 항응고제입니다.' },
  { name: '에독사반', description: '경구용 항응고제, 혈전 예방에 사용됩니다.' },
  { name: '다비가트란', description: '혈전 예방에 사용되는 항응고제입니다.' },
  { name: '피록시캄', description: '통증 및 염증 완화를 위한 비스테로이드성 항염증제입니다.' },
  { name: '메페남산', description: '주로 생리통 완화에 사용되는 진통제입니다.' },
  { name: '셀레콕시브', description: '관절염 통증 완화에 사용되는 비스테로이드성 항염증제입니다.' },
  { name: '옴프라졸', description: '위산 분비 억제제로 위염과 위궤양 치료에 사용됩니다.' },
  { name: '에스오메프라졸', description: '위식도 역류질환 치료에 사용되는 위산 분비 억제제입니다.' },
  { name: '판토프라졸', description: '위산 과다 분비로 인한 질환을 치료하는 약물입니다.' },
  { name: '라니티딘', description: '위산 분비를 억제하는 히스타민 H2 차단제입니다.' },
  { name: '시메티딘', description: '위산 분비 억제제로 사용됩니다.' },
  { name: '알마게이트', description: '위산을 중화시키는 제산제입니다.' },
  { name: '마그네슘 하이드록사이드', description: '제산제와 완하제로 사용됩니다.' },
  { name: '메트로니다졸', description: '기생충 및 세균 감염 치료에 사용되는 항생제입니다.' },
  { name: '시프로플록사신', description: '다양한 세균 감염 치료에 사용되는 광범위 항생제입니다.' },
  { name: '레보플록사신', description: '호흡기 및 감염 치료에 사용되는 항생제입니다.' },
  { name: '아목시실린', description: '광범위 항생제, 호흡기 감염 치료에 사용됩니다.' },
  { name: '클라불란산', description: '아목시실린과 함께 사용하여 항생제 효과를 증대시킵니다.' },
  { name: '세프트리악손', description: '광범위 항생제로 다양한 감염을 치료합니다.' },
  { name: '세팔렉신', description: '세팔로스포린계 항생제입니다.' },
  { name: '아지트로마이신', description: '호흡기 및 피부 감염 치료에 사용되는 항생제입니다.' },
  { name: '독시사이클린', description: '여드름 및 감염 치료에 사용되는 테트라사이클린계 항생제입니다.' },
  { name: '클린다마이신', description: '호흡기 및 피부 감염 치료에 효과적인 항생제입니다.' },
  { name: '린코마이신', description: '박테리아 감염을 치료하는 항생제입니다.' },
  { name: '플루코나졸', description: '곰팡이 감염 치료에 사용되는 항진균제입니다.' },
  { name: '케토코나졸', description: '피부 및 손발톱 곰팡이 감염 치료에 사용됩니다.' },
  { name: '이트라코나졸', description: '다양한 곰팡이 감염 치료에 사용됩니다.' },
  { name: '발라시클로버', description: '헤르페스 감염 치료에 사용되는 항바이러스제입니다.' },
  { name: '오셀타미비르', description: '독감 치료에 사용되는 항바이러스제입니다.' },
  { name: '페니토인', description: '간질 치료에 사용되는 항간질제입니다.' },
  { name: '톱피라메이트', description: '간질과 편두통 예방에 효과적인 약물입니다.' },
  { name: '리튬', description: '양극성 장애 치료에 사용되는 약물입니다.' },
  { name: '할로페리돌', description: '정신분열증 치료에 사용되는 항정신병제입니다.' },
  { name: '클로자핀', description: '정신분열증 치료에 효과적인 항정신병제입니다.' },
  { name: '리스페리돈', description: '정신분열증 및 양극성 장애 치료에 사용되는 항정신병제입니다.' },
  { name: '올란자핀', description: '정신분열증 치료에 사용됩니다.' },
  { name: '아리피프라졸', description: '정신분열증과 양극성 장애 치료에 사용됩니다.' },
  { name: '케토티펜', description: '천식 예방 및 알레르기 증상 완화에 사용됩니다.' },
  { name: '로라타딘', description: '알레르기 증상을 완화하는 항히스타민제입니다.' },
  { name: '세티리진', description: '알레르기 비염 및 두드러기 증상을 완화합니다.' },
  { name: '펙소페나딘', description: '알레르기 증상 치료에 효과적인 항히스타민제입니다.' },
  { name: '디펜히드라민', description: '알레르기 증상 완화 및 수면제 역할을 합니다.' },
  { name: '몬테루카스트', description: '천식 및 알레르기 치료에 사용됩니다.' },
  { name: '살메테롤', description: '천식 및 만성폐쇄성폐질환(COPD) 치료에 사용됩니다.' },
  { name: '부데소나이드', description: '흡입용 스테로이드로 천식 및 알레르기 비염을 치료합니다.' },
  { name: '플루티카손', description: '천식과 비염 치료에 사용되는 흡입용 스테로이드제입니다.' },
  { name: '테오필린', description: '천식 및 만성폐쇄성폐질환(COPD) 치료에 사용됩니다.' },
  { name: '레보티록신', description: '갑상선 기능 저하증 치료에 사용되는 약물입니다.' },
  { name: '인슐린', description: '당뇨병 치료에 필수적인 호르몬입니다.' },
  { name: '글리메피리드', description: '2형 당뇨병 치료에 사용되는 혈당 조절제입니다.' },
  { name: '메트포르민', description: '2형 당뇨병 치료에 널리 사용되는 약물입니다.' },
  { name: '글리피지드', description: '2형 당뇨병 치료에 사용됩니다.' },
  { name: '피오글리타존', description: '2형 당뇨병 치료에 효과적인 약물입니다.' },
  { name: '비타민 A', description: '시력 보호와 면역 기능 강화, 피부 건강 개선에 도움을 줍니다.' },
  { name: '비타민 B1', description: '에너지 대사와 신경계 건강 유지, 피로 회복에 도움을 줍니다.' },
  { name: '비타민 B2', description: '에너지 생성과 피부, 눈 건강 유지, 철분 흡수 촉진에 기여합니다.' },
  { name: '비타민 B3', description: '콜레스테롤 관리와 뇌 기능 개선, 피부 건강에 도움이 됩니다.' },
  { name: '비타민 B5', description: '호르몬 합성과 상처 치유 촉진, 에너지 대사 촉진에 효과적입니다.' },
  { name: '비타민 B6', description: '신경계 기능 유지, 면역력 강화, 단백질 대사 촉진에 기여합니다.' },
  { name: '비타민 B7', description: '머리카락과 손톱 건강, 에너지 생성, 피부 건강에 도움이 됩니다.' },
  { name: '비타민 B9', description: '세포 성장과 재생, 임신 중 태아 발달, 적혈구 생성에 필요합니다.' },
  { name: '비타민 B12', description: '신경 건강 유지, 적혈구 생성, DNA 합성에 중요한 역할을 합니다.' },
  { name: '비타민 C', description: '면역력 강화, 항산화 작용, 피부 콜라겐 형성에 기여합니다.' },
  { name: '비타민 D', description: '뼈 건강 유지와 면역력 강화, 칼슘 흡수 촉진에 도움을 줍니다.' },
  { name: '비타민 E', description: '항산화 작용을 통해 피부 노화 방지와 면역력 강화에 효과적입니다.' },
  { name: '비타민 K', description: '혈액 응고, 뼈 건강 유지, 칼슘 대사에 중요한 역할을 합니다.' },
  
  // 미네랄
  { name: '칼슘', description: '뼈와 치아 건강 유지, 근육 기능과 신경 신호 전달에 필요합니다.' },
  { name: '마그네슘', description: '근육 이완과 에너지 생성, 신경 기능 유지에 기여합니다.' },
  { name: '철분', description: '적혈구 생성과 산소 운반, 에너지 대사에 중요한 역할을 합니다.' },
  { name: '아연', description: '면역 기능과 세포 성장, 재생, 상처 치유에 도움이 됩니다.' },
  { name: '셀레늄', description: '항산화 작용과 면역력 강화, 갑상선 기능 지원에 필요합니다.' },
  { name: '구리', description: '철분 대사, 면역력 유지, 신경 건강에 기여합니다.' },
  { name: '요오드', description: '갑상선 호르몬 생산과 대사 조절, 뇌 발달 지원에 필요합니다.' },
  { name: '칼륨', description: '혈압 조절과 근육 기능, 전해질 균형 유지에 도움이 됩니다.' },
  
  // 필수 지방산
  { name: '오메가-3', description: '심혈관 건강 개선과 뇌 기능 개선, 염증 감소에 기여합니다.' },
  { name: '오메가-6', description: '피부 건강과 뇌 기능 지원, 에너지 대사 촉진에 필요합니다.' },
  
  // 항산화제
  { name: '코엔자임 Q10', description: '세포 에너지 생성과 항산화 작용, 심장 건강 개선에 기여합니다.' },
  { name: '루테인', description: '눈 건강과 항산화 작용, 황반변성 예방에 도움이 됩니다.' },
  { name: '레시틴', description: '간 기능 강화와 세포막 보호, 콜레스테롤 조절에 기여합니다.' },
  
  // 기타 영양제
  { name: '프로바이오틱스', description: '장 건강 개선과 면역력 강화, 소화 촉진에 도움이 됩니다.' },
  { name: '콜라겐', description: '피부 탄력 개선과 관절 건강, 모발과 손톱 강화에 기여합니다.' },
  { name: '글루코사민', description: '관절 건강 유지와 연골 보호, 염증 감소에 효과적입니다.' },
  { name: 'MSM', description: '관절 통증 완화와 피부 건강 개선, 염증 감소에 도움이 됩니다.' }  
];

// 약-증상 데이터: 각 약물에 대한 정보와 관련된 증상
const drugData = [
  { name: '타이레놀 (Acetaminophen)', symptoms: ['발열', '진통', '두통'] },
  { name: '아스피린 (Aspirin)', symptoms: ['통증', '항염증', '혈전 예방'] },
  { name: '이부프로펜 (Ibuprofen)', symptoms: ['진통', '항염', '발열'] },
  { name: '나프록센 (Naproxen)', symptoms: ['통증', '염증', '비스테로이드성 항염증제'] },
  { name: '디클로페낙 (Diclofenac)', symptoms: ['항염증', '진통'] },
  { name: '덱시부프로펜 (Dexibuprofen)', symptoms: ['진통', '항염'] },
  { name: '트라마돌 (Tramadol)', symptoms: ['중증 통증'] },
  { name: '모르핀 (Morphine)', symptoms: ['강력한 마약성 진통제'] },
  { name: '코데인 (Codeine)', symptoms: ['중등도 통증', '기침 억제'] },
  { name: '메타돈 (Methadone)', symptoms: ['마약성 진통제', '마약 중독 치료'] },
  { name: '옥시코돈 (Oxycodone)', symptoms: ['중증 통증'] },
  { name: '플루옥세틴 (Fluoxetine)', symptoms: ['우울증', '불안'] },
  { name: '파록세틴 (Paroxetine)', symptoms: ['우울증', '불안'] },
  { name: '설트랄린 (Sertraline)', symptoms: ['우울증', '불안'] },
  { name: '에스시탈로프람 (Escitalopram)', symptoms: ['우울증', '불안'] },
  { name: '미르타자핀 (Mirtazapine)', symptoms: ['우울증', '수면 개선'] },
  { name: '아미트립틸린 (Amitriptyline)', symptoms: ['우울증', '신경성 통증'] },
  { name: '발프로산 (Valproic Acid)', symptoms: ['항간질제', '기분 안정'] },
  { name: '카바마제핀 (Carbamazepine)', symptoms: ['항간질제', '삼차신경통'] },
  { name: '라모트리진 (Lamotrigine)', symptoms: ['간질', '양극성 장애'] },
  { name: '가바펜틴 (Gabapentin)', symptoms: ['신경통', '간질'] },
  { name: '프레가발린 (Pregabalin)', symptoms: ['신경통', '간질', '불안'] },
  { name: '리보트릴 (Clonazepam)', symptoms: ['간질', '불안', '공황장애'] },
  { name: '디아제팜 (Diazepam)', symptoms: ['불안', '근육 이완'] },
  { name: '로라제팜 (Lorazepam)', symptoms: ['불안', '수면'] },
  { name: '알프라졸람 (Alprazolam)', symptoms: ['불안', '공황장애'] },
  { name: '프로프라놀롤 (Propranolol)', symptoms: ['고혈압', '부정맥'] },
  { name: '아테놀롤 (Atenolol)', symptoms: ['고혈압', '협심증'] },
  { name: '비소프롤롤 (Bisoprolol)', symptoms: ['고혈압', '심부전'] },
  { name: '칸데사르탄 (Candesartan)', symptoms: ['고혈압', '심부전'] },
  { name: '로사르탄 (Losartan)', symptoms: ['고혈압', '혈관 확장'] },
  { name: '에날라프릴 (Enalapril)', symptoms: ['고혈압', '심부전'] },
  { name: '라미프릴 (Ramipril)', symptoms: ['고혈압', '심부전'] },
  { name: '암로디핀 (Amlodipine)', symptoms: ['고혈압', '협심증'] },
  { name: '니페디핀 (Nifedipine)', symptoms: ['고혈압', '협심증'] },
  { name: '후로세미드 (Furosemide)', symptoms: ['체액 저류', '고혈압'] },
  { name: '히드로클로로티아지드 (Hydrochlorothiazide)', symptoms: ['고혈압'] },
  { name: '스피로놀락톤 (Spironolactone)', symptoms: ['고혈압', '심부전'] },
  { name: '메토프로롤 (Metoprolol)', symptoms: ['고혈압', '협심증'] },
  { name: '클로피도그렐 (Clopidogrel)', symptoms: ['혈전 예방', '항혈소판제'] },
  { name: '와파린 (Warfarin)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '리바록사반 (Rivaroxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '에독사반 (Edoxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '다비가트란 (Dabigatran)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '피록시캄 (Piroxicam)', symptoms: ['통증', '염증', 'NSAID'] },
  { name: '메페남산 (Mefenamic Acid)', symptoms: ['진통제', '생리통'] },
  { name: '셀레콕시브 (Celecoxib)', symptoms: ['관절염 통증', '염증', 'NSAID'] },
  { name: '옴프라졸 (Omeprazole)', symptoms: ['위산 분비 억제', '위염', '위궤양'] },
  { name: '에스오메프라졸 (Esomeprazole)', symptoms: ['역류성 식도염'] },
  { name: '판토프라졸 (Pantoprazole)', symptoms: ['위궤양', '위염'] },
  { name: '라니티딘 (Ranitidine)', symptoms: ['위산 분비 억제'] },
  { name: '시메티딘 (Cimetidine)', symptoms: ['위산 분비 억제'] },
  { name: '알마게이트 (Almagate)', symptoms: ['위산 중화'] },
  { name: '마그네슘 하이드록사이드 (Magnesium Hydroxide)', symptoms: ['제산제', '완하제'] },
  { name: '메트로니다졸 (Metronidazole)', symptoms: ['항생제', '항기생충제'] },
  { name: '시프로플록사신 (Ciprofloxacin)', symptoms: ['항생제', '감염 치료'] },
  { name: '레보플록사신 (Levofloxacin)', symptoms: ['항생제', '감염 치료'] },
  { name: '아목시실린 (Amoxicillin)', symptoms: ['항생제', '감염 치료'] },
  { name: '클라불란산 (Clavulanic Acid)', symptoms: ['항생제 효과 증대'] },
  { name: '세프트리악손 (Ceftriaxone)', symptoms: ['항생제', '감염 치료'] },
  { name: '세팔렉신 (Cephalexin)', symptoms: ['항생제', '감염 치료'] },
  { name: '아지트로마이신 (Azithromycin)', symptoms: ['항생제', '감염 치료'] },
  { name: '독시사이클린 (Doxycycline)', symptoms: ['항생제', '여드름', '감염 치료'] },
  { name: '테트라사이클린 (Tetracycline)', symptoms: ['항생제', '감염 치료'] },
  { name: '클린다마이신 (Clindamycin)', symptoms: ['항생제', '골 및 관절 감염'] },
  { name: '반코마이신 (Vancomycin)', symptoms: ['내성 세균 감염'] },
  { name: '겐타마이신 (Gentamicin)', symptoms: ['항생제', '심각한 감염'] },
  { name: '스트렙토마이신 (Streptomycin)', symptoms: ['결핵'] },
  { name: '리팜핀 (Rifampin)', symptoms: ['결핵'] },
  { name: '이소니아지드 (Isoniazid)', symptoms: ['결핵'] },
  { name: '피라진아미드 (Pyrazinamide)', symptoms: ['결핵'] },
  { name: '에탐부톨 (Ethambutol)', symptoms: ['결핵'] },
  { name: '람부티딘 (Lamivudine)', symptoms: ['HIV', 'B형 간염'] },
  { name: '아시클로버 (Acyclovir)', symptoms: ['헤르페스 감염'] },
  { name: '발라시클로버 (Valacyclovir)', symptoms: ['헤르페스 감염'] },
  { name: '오셀타미비르 (Oseltamivir)', symptoms: ['독감'] },
  { name: '페니토인 (Phenytoin)', symptoms: ['간질'] },
  { name: '톱피라메이트 (Topiramate)', symptoms: ['간질', '편두통 예방'] },
  { name: '리튬 (Lithium)', symptoms: ['양극성 장애'] },
  { name: '할로페리돌 (Haloperidol)', symptoms: ['정신분열증'] },
  { name: '클로자핀 (Clozapine)', symptoms: ['정신분열증'] },
  { name: '리스페리돈 (Risperidone)', symptoms: ['정신분열증'] },
  { name: '올란자핀 (Olanzapine)', symptoms: ['정신분열증'] },
  { name: '아리피프라졸 (Aripiprazole)', symptoms: ['정신분열증'] },
  { name: '케토티펜 (Ketotifen)', symptoms: ['천식 예방'] },
  { name: '로라타딘 (Loratadine)', symptoms: ['알레르기', '비염'] },
  { name: '세티리진 (Cetirizine)', symptoms: ['알레르기'] },
  { name: '펙소페나딘 (Fexofenadine)', symptoms: ['알레르기'] },
  { name: '디펜히드라민 (Diphenhydramine)', symptoms: ['알레르기', '수면'] },
  { name: '몬테루카스트 (Montelukast)', symptoms: ['천식', '알레르기'] },
  { name: '살메테롤 (Salmeterol)', symptoms: ['천식', 'COPD'] },
  { name: '부데소나이드 (Budesonide)', symptoms: ['천식'] },
  { name: '플루티카손 (Fluticasone)', symptoms: ['천식', '알레르기 비염'] },
  { name: '테오필린 (Theophylline)', symptoms: ['천식', 'COPD'] },
  { name: '레보티록신 (Levothyroxine)', symptoms: ['갑상선 기능 저하증'] },
  { name: '인슐린 (Insulin)', symptoms: ['당뇨병'] },
  { name: '글리메피리드 (Glimepiride)', symptoms: ['당뇨병'] },
  { name: '메트포르민 (Metformin)', symptoms: ['당뇨병'] },
  { name: '글리피지드 (Glipizide)', symptoms: ['당뇨병'] },
  { name: '피오글리타존 (Pioglitazone)', symptoms: ['당뇨병'] },

];

//약물 상세정보
const drugData3 = [
 { name: '타이레놀', description: '일일 복용 횟수: 1~4회, 복용 간격: 4~6시간 간격, 복용 시간: 필요할 때, 공복 혹은 식사와 상관없이 복용 가능' },
 { name: '아스피린', description: '일일 복용 횟수: 1~3회, 복용 간격: 4~6시간 간격, 복용 시간: 식사 후 (위장 보호를 위해)' },
 { name: '비타민 C', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식후' },
 { name: '이부프로펜', description: '일일 복용 횟수: 1~3회 (최대 4회), 복용 간격: 6~8시간 간격, 복용 시간: 식사 후 (위장 자극을 줄이기 위해)' },
 { name: '나프록센', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '디클로페낙', description: '일일 복용 횟수: 2~3회, 복용 간격: 8~12시간 간격, 복용 시간: 식사 후' },
 { name: '덱시부프로펜', description: '일일 복용 횟수: 1~3회, 복용 간격: 4~6시간 간격, 복용 시간: 식사 후' },
 { name: '트라마돌', description: '일일 복용 횟수: 1~2회, 복용 간격: 4~6시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '모르핀', description: '일일 복용 횟수: 처방에 따라 다름, 복용 간격: 12시간 또는 필요에 따라, 복용 시간: 처방에 따름 (중증 통증 시 사용)' },
 { name: '코데인', description: '일일 복용 횟수: 1~4회, 복용 간격: 4~6시간 간격, 복용 시간: 식사 후' },
 { name: '메타돈', description: '일일 복용 횟수: 처방에 따라 다름 (주로 1회), 복용 간격: 하루에 한 번, 복용 시간: 처방에 따름' },
 { name: '옥시코돈', description: '일일 복용 횟수: 처방에 따름, 복용 간격: 12시간 간격 또는 필요 시, 복용 시간: 처방에 따름' },
 { name: '플루옥세틴', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 (졸음을 유발하지 않기 때문)' },
 { name: '파록세틴', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '설트랄린', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '에스시탈로프람', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '미르타자핀', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 취침 전' },
 { name: '아미트립틸린', description: '일일 복용 횟수: 1~3회, 복용 간격: 8시간 간격, 복용 시간: 취침 전 (졸음을 유발하기 때문)' },
 { name: '발프로산', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '카바마제핀', description: '일일 복용 횟수: 2~4회, 복용 간격: 6~8시간 간격, 복용 시간: 식사 후' },
 { name: '라모트리진', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '가바펜틴', description: '일일 복용 횟수: 3회, 복용 간격: 8시간 간격, 복용 시간: 식사 후' },
 { name: '프레가발린', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '리보트릴', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '디아제팜', description: '일일 복용 횟수: 1~4회, 복용 간격: 4~6시간 간격, 복용 시간: 식사 후' },
 { name: '로라제팜', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 취침 전 또는 필요 시' },
 { name: '알프라졸람', description: '일일 복용 횟수: 1~3회, 복용 간격: 8시간 간격, 복용 시간: 식사 후' },
 { name: '프로프라놀롤', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식전' },
 { name: '아테놀롤', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식전' },
 { name: '비소프롤롤', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '칸데사르탄', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '로사르탄', description: '일일 복용 횟수: 1~2회, 복용 간격: 12~24시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '에날라프릴', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 전 또는 식사와 상관없이' },
 { name: '라미프릴', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 전 또는 식사와 상관없이' },
 { name: '암로디핀', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사와 상관없이' },
 { name: '니페디핀', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '후로세미드', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 아침 또는 점심, 가급적 오전 시간에 복용 (이뇨 작용으로 인한 수면 방해 방지)' },
 { name: '히드로클로로티아지드', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침' },
 { name: '스피로놀락톤', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 함께 또는 식사 후' },
 { name: '메토프로롤', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '클로피도그렐', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사와 상관없이' },
 { name: '와파린', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 하루 중 같은 시간, 보통 저녁 식사 후' },
 { name: '리바록사반', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사 후' },
 { name: '에독사반', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사 후' },
 { name: '다비가트란', description: '일일 복용 횟수: 1~2회, 복용 간격: 12~24시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '피록시캄', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '메페남산', description: '일일 복용 횟수: 1~3회, 복용 간격: 6시간 간격, 복용 시간: 식사 후' },
 { name: '셀레콕시브', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '옴프라졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 공복에 복용' },
 { name: '에스오메프라졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 공복에 복용' },
 { name: '판토프라졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 공복에 복용' },
 { name: '라니티딘', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '시메티딘', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '알마게이트', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '마그네슘 하이드록사이드', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '메트로니다졸', description: '일일 복용 횟수: 2~3회, 복용 간격: 8~12시간 간격, 복용 시간: 식사 후' },
 { name: '시프로플록사신', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이 (단, 우유 및 칼슘 보충제와 함께 복용 피함)' },
 { name: '레보플록사신', description: '일일 복용 횟수: 1~2회, 복용 간격: 12~24시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '아목시실린', description: '일일 복용 횟수: 2~3회, 복용 간격: 8시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '클라불란산', description: '일일 복용 횟수: 2~3회, 복용 간격: 8시간 간격, 복용 시간: 아목시실린과 함께 복용' },
 { name: '세프트리악손', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 주사제로 사용, 식사와 무관' },
 { name: '세팔렉신', description: '일일 복용 횟수: 1~4회, 복용 간격: 6시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '아지트로마이신', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사와 상관없이' },
 { name: '독시사이클린', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후' },
 { name: '클린다마이신', description: '일일 복용 횟수: 2~4회, 복용 간격: 6~8시간 간격, 복용 시간: 식사 후' },
 { name: '린코마이신', description: '일일 복용 횟수: 2~4회, 복용 간격: 6~8시간 간격, 복용 시간: 식사 후' },
 { name: '플루코나졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 처방에 따름' },
 { name: '케토코나졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 처방에 따름' },
 { name: '이트라코나졸', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '발라시클로버', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '오셀타미비르', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '페니토인', description: '일일 복용 횟수: 1~3회, 복용 간격: 8~12시간 간격, 복용 시간: 식사 후 (위장 보호를 위해)' },
 { name: '톱피라메이트', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '리튬', description: '일일 복용 횟수: 1~3회, 복용 간격: 8~12시간 간격, 복용 시간: 식사와 상관없이' },
 { name: '할로페리돌', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '클로자핀', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '리스페리돈', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 처방에 따름' },
 { name: '올란자핀', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 취침 전 (졸음 유발 가능)' },
 { name: '아리피프라졸', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 (졸음 유발 가능성이 낮음)' },
 { name: '케토티펜', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 취침 전 (졸음을 유발할 수 있음)' },
 { name: '로라타딘', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 (졸음을 유발하지 않음)' },
 { name: '세티리진', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 저녁 (졸음을 유발할 수 있음)' },
 { name: '펙소페나딘', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사와 상관없이 (졸음을 유발하지 않음)' },
 { name: '디펜히드라민', description: '일일 복용 횟수: 1~4회, 복용 간격: 4~6시간 간격, 복용 시간: 수면 전 또는 필요 시' },
 { name: '몬테루카스트', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 저녁에 복용 (천식 및 알레르기 증상 예방)' },
 { name: '살메테롤', description: '일일 복용 횟수: 2회, 복용 간격: 12시간 간격, 복용 시간: 아침과 저녁, 흡입제 형태로 사용' },
 { name: '부데소나이드', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 아침과 저녁, 흡입제로 사용' },
 { name: '플루티카손', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 아침과 저녁, 흡입제로 사용' },
 { name: '테오필린', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 후 (위장 보호를 위해)' },
 { name: '레보티록신', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 공복에 복용' },
 { name: '인슐린', description: '일일 복용 횟수: 처방에 따라 다름 (일반적으로 하루 1~4회), 복용 간격: 식사 전 또는 식사 후, 복용 시간: 혈당 수치에 따라 의사의 지시에 따름' },
 { name: '글리메피리드', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 아침 식사 전 또는 식사 중' },
 { name: '메트포르민', description: '일일 복용 횟수: 1~3회, 복용 간격: 8~12시간 간격, 복용 시간: 식사와 함께' },
 { name: '글리피지드', description: '일일 복용 횟수: 1~2회, 복용 간격: 12시간 간격, 복용 시간: 식사 전 또는 식사 중' },
 { name: '피오글리타존', description: '일일 복용 횟수: 1회, 복용 간격: 하루에 한 번, 복용 시간: 식사와 상관없이' }
]

const drugData2 = [
  { name: '타이레놀 (Acetaminophen)', symptoms: ['발열', '진통', '두통'] },
  { name: '아스피린 (Aspirin)', symptoms: ['통증', '항염', '혈전 예방'] },
  { name: '이부프로펜 (Ibuprofen)', symptoms: ['진통', '항염', '발열'] },
  { name: '나프록센 (Naproxen)', symptoms: ['통증', '염증', '비스테로이드성 항염증제'] },
  { name: '디클로페낙 (Diclofenac)', symptoms: ['항염', '진통'] },
  { name: '덱시부프로펜 (Dexibuprofen)', symptoms: ['진통', '항염'] },
  { name: '트라마돌 (Tramadol)', symptoms: ['중증 통증'] },
  { name: '모르핀 (Morphine)', symptoms: ['마약성 진통'] },
  { name: '코데인 (Codeine)', symptoms: ['중등도 통증', '기침'] },
  { name: '메타돈 (Methadone)', symptoms: ['마약성 진통제', '마약중독', '마약 중독'] },
  { name: '옥시코돈 (Oxycodone)', symptoms: ['중증 통증'] },
  { name: '플루옥세틴 (Fluoxetine)', symptoms: ['우울', '불안'] },
  { name: '파록세틴 (Paroxetine)', symptoms: ['우울', '불안'] },
  { name: '설트랄린 (Sertraline)', symptoms: ['우울', '불안'] },
  { name: '에스시탈로프람 (Escitalopram)', symptoms: ['우울', '불안'] },
  { name: '미르타자핀 (Mirtazapine)', symptoms: ['우울', '수면'] },
  { name: '아미트립틸린 (Amitriptyline)', symptoms: ['우울', '신경통'] },
  { name: '발프로산 (Valproic Acid)', symptoms: ['항간질제', '기분 안정'] },
  { name: '카바마제핀 (Carbamazepine)', symptoms: ['항간질제', '신경통'] },
  { name: '라모트리진 (Lamotrigine)', symptoms: ['간질', '양극성 장애'] },
  { name: '가바펜틴 (Gabapentin)', symptoms: ['신경통', '간질'] },
  { name: '프레가발린 (Pregabalin)', symptoms: ['신경통', '간질', '불안'] },
  { name: '리보트릴 (Clonazepam)', symptoms: ['간질', '불안', '공황장애'] },
  { name: '디아제팜 (Diazepam)', symptoms: ['불안', '근육 이완'] },
  { name: '로라제팜 (Lorazepam)', symptoms: ['불안', '수면'] },
  { name: '알프라졸람 (Alprazolam)', symptoms: ['불안', '공황장애'] },
  { name: '프로프라놀롤 (Propranolol)', symptoms: ['고혈압', '부정맥'] },
  { name: '아테놀롤 (Atenolol)', symptoms: ['고혈압', '협심증'] },
  { name: '비소프롤롤 (Bisoprolol)', symptoms: ['고혈압', '심부전'] },
  { name: '칸데사르탄 (Candesartan)', symptoms: ['고혈압', '심부전'] },
  { name: '로사르탄 (Losartan)', symptoms: ['고혈압', '혈관 확장'] },
  { name: '에날라프릴 (Enalapril)', symptoms: ['고혈압', '심부전'] },
  { name: '라미프릴 (Ramipril)', symptoms: ['고혈압', '심부전'] },
  { name: '암로디핀 (Amlodipine)', symptoms: ['고혈압', '협심증'] },
  { name: '니페디핀 (Nifedipine)', symptoms: ['고혈압', '협심증'] },
  { name: '후로세미드 (Furosemide)', symptoms: ['체액 저류', '고혈압'] },
  { name: '히드로클로로티아지드 (Hydrochlorothiazide)', symptoms: ['고혈압'] },
  { name: '스피로놀락톤 (Spironolactone)', symptoms: ['고혈압', '심부전'] },
  { name: '메토프로롤 (Metoprolol)', symptoms: ['고혈압', '협심증'] },
  { name: '클로피도그렐 (Clopidogrel)', symptoms: ['혈전', '항혈소판제'] },
  { name: '와파린 (Warfarin)', symptoms: ['혈전', '항응고제'] },
  { name: '리바록사반 (Rivaroxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '에독사반 (Edoxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '다비가트란 (Dabigatran)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '피록시캄 (Piroxicam)', symptoms: ['통증', '염증', 'NSAID'] },
  { name: '메페남산 (Mefenamic Acid)', symptoms: ['진통제', '생리통'] },
  { name: '셀레콕시브 (Celecoxib)', symptoms: ['관절염 통증', '염증', 'NSAID'] },
  { name: '옴프라졸 (Omeprazole)', symptoms: ['위산 분비 억제', '위염', '위궤양'] },
  { name: '에스오메프라졸 (Esomeprazole)', symptoms: ['역류성 식도염'] },
  { name: '판토프라졸 (Pantoprazole)', symptoms: ['위궤양', '위염'] },
  { name: '라니티딘 (Ranitidine)', symptoms: ['위산 분비'] },
  { name: '시메티딘 (Cimetidine)', symptoms: ['위산 분비'] },
  { name: '알마게이트 (Almagate)', symptoms: ['위산 중화'] },
  { name: '마그네슘 하이드록사이드 (Magnesium Hydroxide)', symptoms: ['제산제', '완하제'] },
  { name: '메트로니다졸 (Metronidazole)', symptoms: ['항생', '항기생충제'] },
  { name: '시프로플록사신 (Ciprofloxacin)', symptoms: ['항생', '감염'] },
  { name: '레보플록사신 (Levofloxacin)', symptoms: ['항생', '감염'] },
  { name: '아목시실린 (Amoxicillin)', symptoms: ['항생', '감염'] },
  { name: '클라불란산 (Clavulanic Acid)', symptoms: ['항생 효과 증대'] },
  { name: '세프트리악손 (Ceftriaxone)', symptoms: ['항생', '감염'] },
  { name: '세팔렉신 (Cephalexin)', symptoms: ['항생', '감염'] },
  { name: '아지트로마이신 (Azithromycin)', symptoms: ['항생', '감염'] },
  { name: '독시사이클린 (Doxycycline)', symptoms: ['항생', '여드름', '감염'] },
  { name: '테트라사이클린 (Tetracycline)', symptoms: ['항생', '감염'] },
  { name: '클린다마이신 (Clindamycin)', symptoms: ['항생', '골','감염', '관절 감염'] },
  { name: '반코마이신 (Vancomycin)', symptoms: ['내성 세균 감염'] },
  { name: '겐타마이신 (Gentamicin)', symptoms: ['항생', '심각한', '감염'] },
  { name: '스트렙토마이신 (Streptomycin)', symptoms: ['결핵'] },
  { name: '리팜핀 (Rifampin)', symptoms: ['결핵'] },
  { name: '이소니아지드 (Isoniazid)', symptoms: ['결핵'] },
  { name: '피라진아미드 (Pyrazinamide)', symptoms: ['결핵'] },
  { name: '에탐부톨 (Ethambutol)', symptoms: ['결핵'] },
  { name: '람부티딘 (Lamivudine)', symptoms: ['HIV', 'B형 간염'] },
  { name: '아시클로버 (Acyclovir)', symptoms: ['헤르페스'] },
  { name: '발라시클로버 (Valacyclovir)', symptoms: ['헤르페스'] },
  { name: '오셀타미비르 (Oseltamivir)', symptoms: ['독감'] },
  { name: '페니토인 (Phenytoin)', symptoms: ['간질'] },
  { name: '톱피라메이트 (Topiramate)', symptoms: ['간질', '편두통'] },
  { name: '리튬 (Lithium)', symptoms: ['양극성 장애'] },
  { name: '할로페리돌 (Haloperidol)', symptoms: ['정신분열'] },
  { name: '클로자핀 (Clozapine)', symptoms: ['정신분열'] },
  { name: '리스페리돈 (Risperidone)', symptoms: ['정신분열'] },
  { name: '올란자핀 (Olanzapine)', symptoms: ['정신분열'] },
  { name: '아리피프라졸 (Aripiprazole)', symptoms: ['정신분열'] },
  { name: '케토티펜 (Ketotifen)', symptoms: ['천식'] },
  { name: '로라타딘 (Loratadine)', symptoms: ['알레르기', '비염'] },
  { name: '세티리진 (Cetirizine)', symptoms: ['알레르기'] },
  { name: '펙소페나딘 (Fexofenadine)', symptoms: ['알레르기'] },
  { name: '디펜히드라민 (Diphenhydramine)', symptoms: ['알레르기', '수면'] },
  { name: '몬테루카스트 (Montelukast)', symptoms: ['천식', '알레르기'] },
  { name: '살메테롤 (Salmeterol)', symptoms: ['천식', 'COPD'] },
  { name: '부데소나이드 (Budesonide)', symptoms: ['천식'] },
  { name: '플루티카손 (Fluticasone)', symptoms: ['천식', '알레르기 비염'] },
  { name: '테오필린 (Theophylline)', symptoms: ['천식', 'COPD'] },
  { name: '레보티록신 (Levothyroxine)', symptoms: ['갑상선','기능 저하'] },
  { name: '인슐린 (Insulin)', symptoms: ['당뇨'] },
  { name: '글리메피리드 (Glimepiride)', symptoms: ['당뇨'] },
  { name: '메트포르민 (Metformin)', symptoms: ['당뇨'] },
  { name: '글리피지드 (Glipizide)', symptoms: ['당뇨'] },
  { name: '피오글리타존 (Pioglitazone)', symptoms: ['당뇨'] },
  
  { name: '비타민 A (Vitamin A)', symptoms: ['시력', '면역', '피부'] },
  { name: '비타민 B1 (Thiamine)', symptoms: ['에너지', '신경계', '피로'] },
  { name: '비타민 B2 (Riboflavin)', symptoms: ['에너지', '피부', ,'눈', '철분'] },
  { name: '비타민 B3 (Niacin)', symptoms: ['콜레스테롤', '뇌', '피부'] },
  { name: '비타민 B5 (Pantothenic Acid)', symptoms: ['호르몬', '상처', '에너지'] },
  { name: '비타민 B6 (Pyridoxine)', symptoms: ['신경계', '면역력', '단백질'] },
  { name: '비타민 B7 (Biotin)', symptoms: ['머리카락', '손톱', '에너지', '피부'] },
  { name: '비타민 B9 (Folic Acid)', symptoms: ['세포', '임신', '적혈구'] },
  { name: '비타민 B12 (Cobalamin)', symptoms: ['신경', '적혈구', 'DNA'] },
  { name: '비타민 C (Ascorbic Acid)', symptoms: ['면역력', '항산화', '콜라겐'] },
  { name: '비타민 D (Cholecalciferol)', symptoms: ['뼈', '면역력', '칼슘'] },
  { name: '비타민 E (Tocopherol)', symptoms: ['항산화', '피부 노화', '면역력'] },
  { name: '비타민 K (Phylloquinone)', symptoms: ['혈액', '뼈', '칼슘'] },
  
  // 미네랄
  { name: '칼슘 (Calcium)', symptoms: ['뼈', '치아', '근육', '신경'] },
  { name: '마그네슘 (Magnesium)', symptoms: ['근육', '이완', '에너지', '신경'] },
  { name: '철분 (Iron)', symptoms: ['적혈구', '산소', '에너지'] },
  { name: '아연 (Zinc)', symptoms: ['면역', '세포', '상처'] },
  { name: '셀레늄 (Selenium)', symptoms: ['항산화', '면역력', '갑상선'] },
  { name: '구리 (Copper)', symptoms: ['철분', '면역력', '신경'] },
  { name: '요오드 (Iodine)', symptoms: ['갑상선', '대사', '뇌'] },
  { name: '칼륨 (Potassium)', symptoms: ['혈압', '근육', '전해질 균형 유지'] },
  
  // 필수 지방산
  { name: '오메가-3 (Omega-3 Fatty Acids)', symptoms: ['심혈관', '뇌', '염증'] },
  { name: '오메가-6 (Omega-6 Fatty Acids)', symptoms: ['피부', '뇌', '에너지'] },
  
  // 항산화제
  { name: '코엔자임 Q10 (Coenzyme Q10)', symptoms: ['세포', '항산화', '심장'] },
  { name: '루테인 (Lutein)', symptoms: ['눈', '항산화', '황반변성'] },
  { name: '레시틴 (Lecithin)', symptoms: ['간', '세포막', '콜레스테롤'] },
  
  // 기타 영양제
  { name: '프로바이오틱스 (Probiotics)', symptoms: ['장', '면역력', '소화'] },
  { name: '콜라겐 (Collagen)', symptoms: ['피부', '관절', '모발', '손톱'] },
  { name: '글루코사민 (Glucosamine)', symptoms: ['관절', '연골', '염증'] },
  { name: 'MSM (Methylsulfonylmethane)', symptoms: ['관절', '피부', '염증'] }
];
