// 약-증상 데이터: 각 약물에 대한 정보와 관련된 증상
const drugData = [
  { name: '타이레놀 (Acetaminophen)', symptoms: ['발열', '진통', '두통'] },
  { name: '아스피린 (Aspirin)', symptoms: ['통증', '항염증', '혈전 예방'] },
  { name: '이부프로펜 (Ibuprofen)', symptoms: ['진통', '항염', '발열'] },
  { name: '나프록센 (Naproxen)', symptoms: ['통증', '염증', '비스테로이드성 항염증제'] },
  { name: '디클로페낙 (Diclofenac)', symptoms: ['항염증', '진통'] },
  { name: '덱시부프로펜 (Dexibuprofen)', symptoms: ['진통', '항염'] },
  { name: '트라마돌 (Tramadol)', symptoms: ['중증 통증'] },
  { name: '모르핀 (Morphine)', symptoms: ['강력한 마약성 진통제'] },
  { name: '코데인 (Codeine)', symptoms: ['중등도 통증', '기침 억제'] },
  { name: '메타돈 (Methadone)', symptoms: ['마약성 진통제', '마약 중독 치료'] },
  { name: '옥시코돈 (Oxycodone)', symptoms: ['중증 통증'] },
  { name: '플루옥세틴 (Fluoxetine)', symptoms: ['우울증', '불안'] },
  { name: '파록세틴 (Paroxetine)', symptoms: ['우울증', '불안'] },
  { name: '설트랄린 (Sertraline)', symptoms: ['우울증', '불안'] },
  { name: '에스시탈로프람 (Escitalopram)', symptoms: ['우울증', '불안'] },
  { name: '미르타자핀 (Mirtazapine)', symptoms: ['우울증', '수면 개선'] },
  { name: '아미트립틸린 (Amitriptyline)', symptoms: ['우울증', '신경성 통증'] },
  { name: '발프로산 (Valproic Acid)', symptoms: ['항간질제', '기분 안정'] },
  { name: '카바마제핀 (Carbamazepine)', symptoms: ['항간질제', '삼차신경통'] },
  { name: '라모트리진 (Lamotrigine)', symptoms: ['간질', '양극성 장애'] },
  { name: '가바펜틴 (Gabapentin)', symptoms: ['신경통', '간질'] },
  { name: '프레가발린 (Pregabalin)', symptoms: ['신경통', '간질', '불안'] },
  { name: '리보트릴 (Clonazepam)', symptoms: ['간질', '불안', '공황장애'] },
  { name: '디아제팜 (Diazepam)', symptoms: ['불안', '근육 이완'] },
  { name: '로라제팜 (Lorazepam)', symptoms: ['불안', '수면'] },
  { name: '알프라졸람 (Alprazolam)', symptoms: ['불안', '공황장애'] },
  { name: '프로프라놀롤 (Propranolol)', symptoms: ['고혈압', '부정맥'] },
  { name: '아테놀롤 (Atenolol)', symptoms: ['고혈압', '협심증'] },
  { name: '비소프롤롤 (Bisoprolol)', symptoms: ['고혈압', '심부전'] },
  { name: '칸데사르탄 (Candesartan)', symptoms: ['고혈압', '심부전'] },
  { name: '로사르탄 (Losartan)', symptoms: ['고혈압', '혈관 확장'] },
  { name: '에날라프릴 (Enalapril)', symptoms: ['고혈압', '심부전'] },
  { name: '라미프릴 (Ramipril)', symptoms: ['고혈압', '심부전'] },
  { name: '암로디핀 (Amlodipine)', symptoms: ['고혈압', '협심증'] },
  { name: '니페디핀 (Nifedipine)', symptoms: ['고혈압', '협심증'] },
  { name: '후로세미드 (Furosemide)', symptoms: ['체액 저류', '고혈압'] },
  { name: '히드로클로로티아지드 (Hydrochlorothiazide)', symptoms: ['고혈압'] },
  { name: '스피로놀락톤 (Spironolactone)', symptoms: ['고혈압', '심부전'] },
  { name: '메토프로롤 (Metoprolol)', symptoms: ['고혈압', '협심증'] },
  { name: '클로피도그렐 (Clopidogrel)', symptoms: ['혈전 예방', '항혈소판제'] },
  { name: '와파린 (Warfarin)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '리바록사반 (Rivaroxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '에독사반 (Edoxaban)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '다비가트란 (Dabigatran)', symptoms: ['혈전 예방', '항응고제'] },
  { name: '피록시캄 (Piroxicam)', symptoms: ['통증', '염증', 'NSAID'] },
  { name: '메페남산 (Mefenamic Acid)', symptoms: ['진통제', '생리통'] },
  { name: '셀레콕시브 (Celecoxib)', symptoms: ['관절염 통증', '염증', 'NSAID'] },
  { name: '옴프라졸 (Omeprazole)', symptoms: ['위산 분비 억제', '위염', '위궤양'] },
  { name: '에스오메프라졸 (Esomeprazole)', symptoms: ['역류성 식도염'] },
  { name: '판토프라졸 (Pantoprazole)', symptoms: ['위궤양', '위염'] },
  { name: '라니티딘 (Ranitidine)', symptoms: ['위산 분비 억제'] },
  { name: '시메티딘 (Cimetidine)', symptoms: ['위산 분비 억제'] },
  { name: '알마게이트 (Almagate)', symptoms: ['위산 중화'] },
  { name: '마그네슘 하이드록사이드 (Magnesium Hydroxide)', symptoms: ['제산제', '완하제'] },
  { name: '메트로니다졸 (Metronidazole)', symptoms: ['항생제', '항기생충제'] },
  { name: '시프로플록사신 (Ciprofloxacin)', symptoms: ['항생제', '감염 치료'] },
  { name: '레보플록사신 (Levofloxacin)', symptoms: ['항생제', '감염 치료'] },
  { name: '아목시실린 (Amoxicillin)', symptoms: ['항생제', '감염 치료'] },
  { name: '클라불란산 (Clavulanic Acid)', symptoms: ['항생제 효과 증대'] },
  { name: '세프트리악손 (Ceftriaxone)', symptoms: ['항생제', '감염 치료'] },
  { name: '세팔렉신 (Cephalexin)', symptoms: ['항생제', '감염 치료'] },
  { name: '아지트로마이신 (Azithromycin)', symptoms: ['항생제', '감염 치료'] },
  { name: '독시사이클린 (Doxycycline)', symptoms: ['항생제', '여드름', '감염 치료'] },
  { name: '테트라사이클린 (Tetracycline)', symptoms: ['항생제', '감염 치료'] },
  { name: '클린다마이신 (Clindamycin)', symptoms: ['항생제', '골 및 관절 감염'] },
  { name: '반코마이신 (Vancomycin)', symptoms: ['내성 세균 감염'] },
  { name: '겐타마이신 (Gentamicin)', symptoms: ['항생제', '심각한 감염'] },
  { name: '스트렙토마이신 (Streptomycin)', symptoms: ['결핵'] },
  { name: '리팜핀 (Rifampin)', symptoms: ['결핵'] },
  { name: '이소니아지드 (Isoniazid)', symptoms: ['결핵'] },
  { name: '피라진아미드 (Pyrazinamide)', symptoms: ['결핵'] },
  { name: '에탐부톨 (Ethambutol)', symptoms: ['결핵'] },
  { name: '람부티딘 (Lamivudine)', symptoms: ['HIV', 'B형 간염'] },
  { name: '아시클로버 (Acyclovir)', symptoms: ['헤르페스 감염'] },
  { name: '발라시클로버 (Valacyclovir)', symptoms: ['헤르페스 감염'] },
  { name: '오셀타미비르 (Oseltamivir)', symptoms: ['독감'] },
  { name: '페니토인 (Phenytoin)', symptoms: ['간질'] },
  { name: '톱피라메이트 (Topiramate)', symptoms: ['간질', '편두통 예방'] },
  { name: '리튬 (Lithium)', symptoms: ['양극성 장애'] },
  { name: '할로페리돌 (Haloperidol)', symptoms: ['정신분열증'] },
  { name: '클로자핀 (Clozapine)', symptoms: ['정신분열증'] },
  { name: '리스페리돈 (Risperidone)', symptoms: ['정신분열증'] },
  { name: '올란자핀 (Olanzapine)', symptoms: ['정신분열증'] },
  { name: '아리피프라졸 (Aripiprazole)', symptoms: ['정신분열증'] },
  { name: '케토티펜 (Ketotifen)', symptoms: ['천식 예방'] },
  { name: '로라타딘 (Loratadine)', symptoms: ['알레르기', '비염'] },
  { name: '세티리진 (Cetirizine)', symptoms: ['알레르기'] },
  { name: '펙소페나딘 (Fexofenadine)', symptoms: ['알레르기'] },
  { name: '디펜히드라민 (Diphenhydramine)', symptoms: ['알레르기', '수면'] },
  { name: '몬테루카스트 (Montelukast)', symptoms: ['천식', '알레르기'] },
  { name: '살메테롤 (Salmeterol)', symptoms: ['천식', 'COPD'] },
  { name: '부데소나이드 (Budesonide)', symptoms: ['천식'] },
  { name: '플루티카손 (Fluticasone)', symptoms: ['천식', '알레르기 비염'] },
  { name: '테오필린 (Theophylline)', symptoms: ['천식', 'COPD'] },
  { name: '레보티록신 (Levothyroxine)', symptoms: ['갑상선 기능 저하증'] },
  { name: '인슐린 (Insulin)', symptoms: ['당뇨병'] },
  { name: '글리메피리드 (Glimepiride)', symptoms: ['당뇨병'] },
  { name: '메트포르민 (Metformin)', symptoms: ['당뇨병'] },
  { name: '글리피지드 (Glipizide)', symptoms: ['당뇨병'] },
  { name: '피오글리타존 (Pioglitazone)', symptoms: ['당뇨병'] },
];
